### PR TITLE
Implement the complete MC2010 Level II model and compute model uncertainty

### PR DESCRIPTION
**Pull request by rozsasarpi**
The changes are not harmonized with the rest of the code! the model uncertainty estimation code works only with `mc2010-current`. That will be done in a separate pull request, this only focuses on the implementation of the formula and estimating the model uncertainty.

For a reference, the model uncertainty for the current EC2 formula (only eq. (6-2)) (the mean has a small relevance):

| mean | cv  |
| ------ | ----|
|0.2047 | 0.2376 | 

Related to #11.

### CODE REVIEW

**Comment by rozsasarpi** [comment]
The model uncertainty for the current EC2 formula (only eq. (6-2)) with the implementation of [6f6ddec](https://github.com/TNO/shear_calibration/pull/6/commits/6f6ddec92cc16a0aaac5dab0e3c7d644bd3b796f) (the mean has a small relevance):

| mean | cv  |
| ------ | ----|
|1.3031 | 0.2082 |

**Comment by rozsasarpi** [comment]
What does this line refer to?
https://github.com/TNO/shear_calibration/blob/6f6ddec92cc16a0aaac5dab0e3c7d644bd3b796f/code/shared_utils/resistance_models/MC2010_level_II_codified_2019.m#L51

Eq. (7.3-26) is for members with shear reinforcement in the MC2010 document that I have.

**Comment by slobbeat** [comment]
It seems a copy-paste issue (the formula is exactly the same as EC2). MC2010 has no v_min, so it can be removed.

**Comment by rozsasarpi** [comment]
Done, see the commit after your comment.

**Comment by slobbeat** [comment]
The code was checked on the consistency between implemented eqs & rules and how it is written in the fib MC2010. I think it is correct.

**Review by slobbeat — APPROVED** [review]
I checked it on the consistency between implemented eqs & rules and how it is written in the fib MC2010, and I think it is correct.

**Comment by rozsasarpi** [comment]
Thanks.

I also would like to know if there are some variables in the data base that could still be used in this formula (beyond those that we already use.) maybe `mvd`? #5

**Comment by rozsasarpi** [comment]
Summary of the (indicative) results after the latest changes:

* MC2010 model uncertainty:

| mean | cv  | repr
| ------ | ----| -- |
|1.344 | 0.1924 | 1.079 |

* optimal partial factor with the simple load combination: `gamma_C = 1.324`.

**Pull request merged**
